CREATE TRIGGER supprimerSite ON SITE
INSTEAD OF DELETE AS
BEGIN
	DECLARE @idSite int
	SELECT @idSite=idSite FROM DELETED
	DELETE FROM MATERIEL WHERE idSite=@idSite
	DELETE FROM SITE WHERE idSite=@idSite
END